version: "3.8"
services:

  dev:
    image: hongyuanyang/my-dev:mvn3.6.3-openjdk-11
    ports:
      - "8081:80"
      - "5000:5000"
    container_name: dev-code-server
    volumes: 
      - ./project:/root/project
