version: "3.8"
services:

  dev:
    image: hongyuanyang/my-dev:mvn3.6.3-openjdk-11
    ports:
      - "8081:80"
      - "8080:8080"
    container_name: dev-code-server
    volumes: 
      - ./project:/root/project
  mysql:
    image: mysql:5.6
    ports:
      - "3307:3306"
    container_name: dev-mysql
    env_file:
      - "myenv"
