version: '3.8'
  
services:

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    container_name: mysql
    env_file:
      - "myenv"
  tools:
    image: hongyuanyang/my-dev:internal-tools
    ports:
      - "8888:8080"
    container_name: tools
    environment:
      - TZ=Asia/Taipei
    depends_on:
      - mysql
  metabase:
    image: metabase/metabase:v0.37.2
    container_name: metabase
    ports:
      - 13000:3000
    volumes:
      - ./app/data:/var/lib/metabase/data
    environment:
      TZ: 'Asia/Taipei'
    depends_on:
      - tools
